-- Setup

CREATE TABLE Employees
(
  empID number generated by default AS identity, 
  empName varchar2(20) NOT NULL, 
  PRIMARY KEY (empID)
);


CREATE TABLE Customers
(
  custID number generated by default AS identity, 
  custName varchar2(20), 
  PRIMARY KEY (custID)
);

CREATE TABLE Sales
(
  salesID number generated by default AS identity, 
  empID number NOT NULL, 
  custID number NOT NULL, 
  PRIMARY KEY (salesID), 
  FOREIGN KEY (empID) REFERENCES Employees(empID),
  FOREIGN KEY (custID) REFERENCES Customers(custID),
);

-- Create a view

CREATE VIEW vSalesInfo AS 
SELECT Sales.salesID "ID", 
       Employees.empName "Employee Name", 
       Customers.custName "Customer Name"
  FROM 
    Employees, 
    Customers, 
    Sales
  WHERE 
    Employees.empID = Sales.empID
    AND
    Customers.custID = Sales.custID;
-- returned: "View VSALESINFO created."

-- To see the view

SELECT * 
  FROM vSalesInfo;


-- Highest salesID - using a function

SELECT MAX(salesID) 
  FROM Sales;
  
-- Meaningless examples sum of IDs and average of IDs

SELECT SUM(salesID) 
  FROM Sales;
  
SELECT AVG(salesID) 
  FROM Sales;
  
-- Setup

DROP TABLE Customers;

CREATE TABLE Customers
(
  custID number generated by default AS identity, 
  custName varchar2(20), 
  fullName varchar2(51),
  PRIMARY KEY (custID)
);

-- User-defined function

SELECT custName, 
       fullName, 
       SUBSTR(fullName, 1, (INSTR(fullName, ' ') - 1)) AS "First Name",
       SUBSTR(fullName, (INSTR(fullName, ' ') + 1))    AS "Last Name"
  FROM Customers;
  
