-- Setup

CREATE TABLE Employees
(
  empID number generated by default AS identity, 
  empName varchar2(20) NOT NULL, 
  PRIMARY KEY (empID)
);


CREATE TABLE Customers
(
  custID number generated by default AS identity, 
  custName varchar2(20), 
  PRIMARY KEY (custID)
);

CREATE TABLE Sales
(
  salesID number generated by default AS identity, 
  empID number NOT NULL, 
  custID number NOT NULL, 
  PRIMARY KEY (salesID), 
  FOREIGN KEY (empID) REFERENCES Employees(empID),
  FOREIGN KEY (custID) REFERENCES Customers(custID),
);

-- Sales table has only numbers in it. 
-- Get a readable format

SELECT e.empName "Employee",
       c.custName "Customer"
  FROM 
    Employees e, 
    Customers c, 
    Sales s
  WHERE 
    e.empID = s.empID
    AND
    c.custID = s.custID;
