CREATE TABLE Customers
(
  custID number generated by default AS identity, 
  custName varchar2(20), 
  contact_fname varchar2(20), 
  contact_lname varchar2(20), 
  contact_full_name varchar2(51) generated always AS (contact_fname || ' ' || contact_lname),
  PRIMARY KEY (custID)
);

CREATE TABLE Employees
(
  empID number generated by default AS identity, 
  last_name varchar2(20) NOT NULL, 
  first_name varchar2(20) NOT NULL, 
  email varchar2(20)
);
