-- USING demonstration

  -- Setup

CREATE TABLE agents
(
  agentId NUMBER generated by default ON NULL AS identity,
  agentName varchar(20) NOT NULL
);

INSERT INTO agents (agentName)
  VALUES ('oracle');
INSERT INTO agents (agentName)
  VALUES ('microsoft');

CREATE TABLE agentInfo 
(
  agentInfoId NUMBER generated by default ON NULL AS identity,
  agentId NUMBER NOT NULL,
  agentDescription varchar(20) NOT NULL
);

INSERT INTO agentInfo (agentId, agentDescription) 
  VALUES (1, 'active directory');
INSERT INTO agentInfo (agentId, agentDescription) 
  VALUES (2, 'SQL developer');
  
-- Now the demonstration

SELECT agentName,
       agentDescription 
  FROM 
    agents 
      JOIN 
    agentInfo
      USING (agentId);
